### ISSUE TITLE
meson install version

### ISSUE THREAD

**Issue by Zoyolin** [drobilla/ingen#33]
Hi, I'm on ubuntu 20.04, when building raul or ingen I end up in a bit of a picke, if I may... It's my first time trying to build raul (in order to build ingen)  I could do with a little help. I also understand that the software is under construction and may simply not be buildable.

so for raul, I checked out v2.0.0 ; run meson setup build which can't find autoship nor reuse, I can't find them in the ppas aswell so I move on ; meson build, runs fine ; sudo meson install fails systematically. so I've tried different versions from the ppas and from pip I believe.

Hopefully this is a naive question. 
Is there a way forward from where I am?
what meson version do you use?
what commit of raul is best for building ingen later on?

```sh
ME@ME-srv:~/bin/rau/build$ /usr/bin/meson --version  
0.53.2 
ME@ME-srv:~/bin/rau/build$ sudo /usr/bin/meson install
ninja: Entering directory `.'
ninja: no work to do.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 514, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 330, in do_install
    d = pickle.load(ifile)
AttributeError: Can't get attribute 'OctalInt' on <module 'mesonbuild.coredata' from '/usr/lib/python3/dist-packages/mesonbuild/coredata.
'>
```

```sh
ME@ME-srv:~/bin/rau/build$ /home/diag/.local/bin/meson  --version
1.0.1
ME@ME-srv:~/bin/rau/build$ sudo /home/diag/.local/bin/meson install
Traceback (most recent call last):
  File "/home/diag/.local/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
```

```sh
ME@ME-srv:~/bin/rau/build$ /usr/bin/meson --version
0.61.5
ME@ME-srv:~/bin/rau/build$ sudo /usr/bin/meson install
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 148, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 799, in run
    b = build.load(opts.wd)
  File "/usr/lib/python3/dist-packages/mesonbuild/build.py", line 2856, in load
    obj = pickle.load(f)
ModuleNotFoundError: No module named 'mesonbuild.utils'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

Thanks for reading, BR

**Comment by drobilla** [comment]
Hello,None of the missing tools you mentioned are a problem (or useful at all for anything but development anyway), so that's fine. As far as installation, it looks like your meson install itself is broken.  Judging by the log, it looks like you have several versions installed at once and are somehow using both, which... is suspect, let's say.The meson community (the IRC channel is pretty active, maybe they have other support forums, not sure) can probably help.  Your meson install itself is definitely broken somehow, but I don't have any more specific ideas that might help. Removing any and all meson installations, system and local, from your system and installing one and trying with that might be a good idea to try though.Best,-- drOn Mar 22, 2023 21:10, Zoyolin ***@***.***> wrote:
Hi, I'm on ubuntu 20.04, when building raul or ingen I end up in a bit of a picke, if I may... It's my first time trying to build raul (in order to build ingen)  I could do with a little help. I also understand that the software is under construction and may simply not be buildable.
so for raul, I checked out v2.0.0 ; run meson setup build which can't find autoship nor reuse, I can't find them in the ppas aswell so I move on ; meson build, runs fine ; sudo meson install fails systematically. so I've tried different versions from the ppas and from pip I believe.
Hopefully this is a naive question.
Is there a way forward from where I am?
what meson version do you use?
what commit of raul is best for building ingen later on?
***@***.***:~/bin/rau/build$ /usr/bin/meson --version  
0.53.2 
***@***.***:~/bin/rau/build$ sudo /usr/bin/meson install
ninja: Entering directory `.'
ninja: no work to do.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 514, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 330, in do_install
    d = pickle.load(ifile)
AttributeError: Can't get attribute 'OctalInt' on <module 'mesonbuild.coredata' from '/usr/lib/python3/dist-packages/mesonbuild/coredata.
'>
***@***.***:~/bin/rau/build$ /home/diag/.local/bin/meson  --version
1.0.1
***@***.***:~/bin/rau/build$ sudo /home/diag/.local/bin/meson install
Traceback (most recent call last):
  File "/home/diag/.local/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
***@***.***:~/bin/rau/build$ /usr/bin/meson --version
0.61.5
***@***.***:~/bin/rau/build$ sudo /usr/bin/meson install
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 148, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 799, in run
    b = build.load(opts.wd)
  File "/usr/lib/python3/dist-packages/mesonbuild/build.py", line 2856, in load
    obj = pickle.load(f)
ModuleNotFoundError: No module named 'mesonbuild.utils'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
Thanks for reading, BR

**Comment by eli-schwartz** [comment]
> sudo meson install fails systematically. so I've tried different versions from the ppas and from pip I believe.

This is https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip

You cannot `sudo meson install` if you did not install meson with sudo. Doing so will break in several different ways due to loading data produced with (pip installed) meson 1.0.1 by a sudo meson at version 0.53 (installed by ubuntu via apt). If you uninstall the apt-installed version, it simply reports an error because meson isn't installed as far as sudo knows.

The "Getting meson" page describes a couple approaches that can work around this.

**Comment by Zoyolin** [comment]
thanks a lot for the light speed, replies!! I saw them on the spot but my email didn't send ... anyway I'll try again this weekend most likely. I'm feeling very hyped about ingen I had been looking for just that since a few months.

**Comment by drobilla** [comment]
Caveat emptor, ingen isn't really in much of a state for public consumption at the moment, but have fun.

Meson problems seems resolved, so closing this one.

**Comment by Zoyolin** [comment]
I'll clean meson's setup tomorrow then. Thanks a lot for the quick answer

23 Mar 2023 01:24:06 David Robillard ***@***.***>:

>
