### ISSUE TITLE
ImportError: No module named waflib

### ISSUE THREAD

**Issue by mark-orion** [drobilla/ingen#9]
Not sure if I am doing something wrong or if there is something missing.
And trying to pull the submodules leads to this:
mark@alcyone:~/apps/src/ingen$ git submodule update --init --recursive
Submodule 'waflib' (http://git.drobilla.net/autowaf) registered for path 'waflib'
Cloning into '/home/mark/apps/src/ingen/waflib'...
fatal: repository 'http://git.drobilla.net/autowaf/' not found

**Comment by loki42** [comment]
I've fixed this issue but it's a bit dodgy. Basically I just changed the submodule to point to the one on github and made sure I had the latest of the submodule. It seems like it can't find the submodule that's being referenced. It now builds fine.

**Comment by drobilla** [comment]
Sorry, git at drobilla.net is a bit stale, I mainly use Gitlab these days.  Somebody is squatting the "lv2" project on Github so I'm having a hard time making everything work on all the hosts...

Anyway, thanks for the report, this should be fixed by https://github.com/drobilla/ingen/commit/e32f32a360f2bf8f017ea347b6d1e568c0beaf68
